// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"hype-casino-platform/auth_service/internal/infrastructure/ent_impl/ent/authclient"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// AuthClient is the model entity for the AuthClient schema.
type AuthClient struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ClientType holds the value of the "client_type" field.
	ClientType int `json:"client_type,omitempty"`
	// MerchantID holds the value of the "merchant_id" field.
	MerchantID int64 `json:"merchant_id,omitempty"`
	// Secret holds the value of the "secret" field.
	Secret string `json:"secret,omitempty"`
	// Active holds the value of the "active" field.
	Active bool `json:"active,omitempty"`
	// TokenExpireSecs holds the value of the "token_expire_secs" field.
	TokenExpireSecs int `json:"token_expire_secs,omitempty"`
	// LoginFailedTimes holds the value of the "login_failed_times" field.
	LoginFailedTimes int `json:"login_failed_times,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AuthClientQuery when eager-loading is set.
	Edges        AuthClientEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AuthClientEdges holds the relations/edges for other nodes in the graph.
type AuthClientEdges struct {
	// Users holds the value of the users edge.
	Users []*User `json:"users,omitempty"`
	// Roles holds the value of the roles edge.
	Roles []*Role `json:"roles,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UsersOrErr returns the Users value or an error if the edge
// was not loaded in eager-loading.
func (e AuthClientEdges) UsersOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.Users, nil
	}
	return nil, &NotLoadedError{edge: "users"}
}

// RolesOrErr returns the Roles value or an error if the edge
// was not loaded in eager-loading.
func (e AuthClientEdges) RolesOrErr() ([]*Role, error) {
	if e.loadedTypes[1] {
		return e.Roles, nil
	}
	return nil, &NotLoadedError{edge: "roles"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AuthClient) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case authclient.FieldActive:
			values[i] = new(sql.NullBool)
		case authclient.FieldID, authclient.FieldClientType, authclient.FieldMerchantID, authclient.FieldTokenExpireSecs, authclient.FieldLoginFailedTimes:
			values[i] = new(sql.NullInt64)
		case authclient.FieldSecret:
			values[i] = new(sql.NullString)
		case authclient.FieldCreatedAt, authclient.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AuthClient fields.
func (ac *AuthClient) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case authclient.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ac.ID = int64(value.Int64)
		case authclient.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ac.CreatedAt = value.Time
			}
		case authclient.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ac.UpdatedAt = value.Time
			}
		case authclient.FieldClientType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field client_type", values[i])
			} else if value.Valid {
				ac.ClientType = int(value.Int64)
			}
		case authclient.FieldMerchantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field merchant_id", values[i])
			} else if value.Valid {
				ac.MerchantID = value.Int64
			}
		case authclient.FieldSecret:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field secret", values[i])
			} else if value.Valid {
				ac.Secret = value.String
			}
		case authclient.FieldActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				ac.Active = value.Bool
			}
		case authclient.FieldTokenExpireSecs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field token_expire_secs", values[i])
			} else if value.Valid {
				ac.TokenExpireSecs = int(value.Int64)
			}
		case authclient.FieldLoginFailedTimes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field login_failed_times", values[i])
			} else if value.Valid {
				ac.LoginFailedTimes = int(value.Int64)
			}
		default:
			ac.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AuthClient.
// This includes values selected through modifiers, order, etc.
func (ac *AuthClient) Value(name string) (ent.Value, error) {
	return ac.selectValues.Get(name)
}

// QueryUsers queries the "users" edge of the AuthClient entity.
func (ac *AuthClient) QueryUsers() *UserQuery {
	return NewAuthClientClient(ac.config).QueryUsers(ac)
}

// QueryRoles queries the "roles" edge of the AuthClient entity.
func (ac *AuthClient) QueryRoles() *RoleQuery {
	return NewAuthClientClient(ac.config).QueryRoles(ac)
}

// Update returns a builder for updating this AuthClient.
// Note that you need to call AuthClient.Unwrap() before calling this method if this AuthClient
// was returned from a transaction, and the transaction was committed or rolled back.
func (ac *AuthClient) Update() *AuthClientUpdateOne {
	return NewAuthClientClient(ac.config).UpdateOne(ac)
}

// Unwrap unwraps the AuthClient entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ac *AuthClient) Unwrap() *AuthClient {
	_tx, ok := ac.config.driver.(*txDriver)
	if !ok {
		panic("ent: AuthClient is not a transactional entity")
	}
	ac.config.driver = _tx.drv
	return ac
}

// String implements the fmt.Stringer.
func (ac *AuthClient) String() string {
	var builder strings.Builder
	builder.WriteString("AuthClient(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ac.ID))
	builder.WriteString("created_at=")
	builder.WriteString(ac.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ac.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("client_type=")
	builder.WriteString(fmt.Sprintf("%v", ac.ClientType))
	builder.WriteString(", ")
	builder.WriteString("merchant_id=")
	builder.WriteString(fmt.Sprintf("%v", ac.MerchantID))
	builder.WriteString(", ")
	builder.WriteString("secret=")
	builder.WriteString(ac.Secret)
	builder.WriteString(", ")
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", ac.Active))
	builder.WriteString(", ")
	builder.WriteString("token_expire_secs=")
	builder.WriteString(fmt.Sprintf("%v", ac.TokenExpireSecs))
	builder.WriteString(", ")
	builder.WriteString("login_failed_times=")
	builder.WriteString(fmt.Sprintf("%v", ac.LoginFailedTimes))
	builder.WriteByte(')')
	return builder.String()
}

// AuthClients is a parsable slice of AuthClient.
type AuthClients []*AuthClient
