// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"hype-casino-platform/auth_service/internal/infrastructure/ent_impl/ent/authclient"
	"hype-casino-platform/auth_service/internal/infrastructure/ent_impl/ent/loginrecord"
	"hype-casino-platform/auth_service/internal/infrastructure/ent_impl/ent/predicate"
	"hype-casino-platform/auth_service/internal/infrastructure/ent_impl/ent/role"
	"hype-casino-platform/auth_service/internal/infrastructure/ent_impl/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (uu *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	uu.mutation.Where(ps...)
	return uu
}

// SetUpdatedAt sets the "updated_at" field.
func (uu *UserUpdate) SetUpdatedAt(t time.Time) *UserUpdate {
	uu.mutation.SetUpdatedAt(t)
	return uu
}

// SetAccount sets the "account" field.
func (uu *UserUpdate) SetAccount(s string) *UserUpdate {
	uu.mutation.SetAccount(s)
	return uu
}

// SetNillableAccount sets the "account" field if the given value is not nil.
func (uu *UserUpdate) SetNillableAccount(s *string) *UserUpdate {
	if s != nil {
		uu.SetAccount(*s)
	}
	return uu
}

// SetPassword sets the "password" field.
func (uu *UserUpdate) SetPassword(s string) *UserUpdate {
	uu.mutation.SetPassword(s)
	return uu
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (uu *UserUpdate) SetNillablePassword(s *string) *UserUpdate {
	if s != nil {
		uu.SetPassword(*s)
	}
	return uu
}

// SetPasswordFailTimes sets the "password_fail_times" field.
func (uu *UserUpdate) SetPasswordFailTimes(i int) *UserUpdate {
	uu.mutation.ResetPasswordFailTimes()
	uu.mutation.SetPasswordFailTimes(i)
	return uu
}

// SetNillablePasswordFailTimes sets the "password_fail_times" field if the given value is not nil.
func (uu *UserUpdate) SetNillablePasswordFailTimes(i *int) *UserUpdate {
	if i != nil {
		uu.SetPasswordFailTimes(*i)
	}
	return uu
}

// AddPasswordFailTimes adds i to the "password_fail_times" field.
func (uu *UserUpdate) AddPasswordFailTimes(i int) *UserUpdate {
	uu.mutation.AddPasswordFailTimes(i)
	return uu
}

// SetStatus sets the "status" field.
func (uu *UserUpdate) SetStatus(i int) *UserUpdate {
	uu.mutation.ResetStatus()
	uu.mutation.SetStatus(i)
	return uu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (uu *UserUpdate) SetNillableStatus(i *int) *UserUpdate {
	if i != nil {
		uu.SetStatus(*i)
	}
	return uu
}

// AddStatus adds i to the "status" field.
func (uu *UserUpdate) AddStatus(i int) *UserUpdate {
	uu.mutation.AddStatus(i)
	return uu
}

// SetAuthClientsID sets the "auth_clients" edge to the AuthClient entity by ID.
func (uu *UserUpdate) SetAuthClientsID(id int64) *UserUpdate {
	uu.mutation.SetAuthClientsID(id)
	return uu
}

// SetNillableAuthClientsID sets the "auth_clients" edge to the AuthClient entity by ID if the given value is not nil.
func (uu *UserUpdate) SetNillableAuthClientsID(id *int64) *UserUpdate {
	if id != nil {
		uu = uu.SetAuthClientsID(*id)
	}
	return uu
}

// SetAuthClients sets the "auth_clients" edge to the AuthClient entity.
func (uu *UserUpdate) SetAuthClients(a *AuthClient) *UserUpdate {
	return uu.SetAuthClientsID(a.ID)
}

// AddLoginRecordIDs adds the "login_records" edge to the LoginRecord entity by IDs.
func (uu *UserUpdate) AddLoginRecordIDs(ids ...int64) *UserUpdate {
	uu.mutation.AddLoginRecordIDs(ids...)
	return uu
}

// AddLoginRecords adds the "login_records" edges to the LoginRecord entity.
func (uu *UserUpdate) AddLoginRecords(l ...*LoginRecord) *UserUpdate {
	ids := make([]int64, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return uu.AddLoginRecordIDs(ids...)
}

// SetRolesID sets the "roles" edge to the Role entity by ID.
func (uu *UserUpdate) SetRolesID(id int64) *UserUpdate {
	uu.mutation.SetRolesID(id)
	return uu
}

// SetNillableRolesID sets the "roles" edge to the Role entity by ID if the given value is not nil.
func (uu *UserUpdate) SetNillableRolesID(id *int64) *UserUpdate {
	if id != nil {
		uu = uu.SetRolesID(*id)
	}
	return uu
}

// SetRoles sets the "roles" edge to the Role entity.
func (uu *UserUpdate) SetRoles(r *Role) *UserUpdate {
	return uu.SetRolesID(r.ID)
}

// Mutation returns the UserMutation object of the builder.
func (uu *UserUpdate) Mutation() *UserMutation {
	return uu.mutation
}

// ClearAuthClients clears the "auth_clients" edge to the AuthClient entity.
func (uu *UserUpdate) ClearAuthClients() *UserUpdate {
	uu.mutation.ClearAuthClients()
	return uu
}

// ClearLoginRecords clears all "login_records" edges to the LoginRecord entity.
func (uu *UserUpdate) ClearLoginRecords() *UserUpdate {
	uu.mutation.ClearLoginRecords()
	return uu
}

// RemoveLoginRecordIDs removes the "login_records" edge to LoginRecord entities by IDs.
func (uu *UserUpdate) RemoveLoginRecordIDs(ids ...int64) *UserUpdate {
	uu.mutation.RemoveLoginRecordIDs(ids...)
	return uu
}

// RemoveLoginRecords removes "login_records" edges to LoginRecord entities.
func (uu *UserUpdate) RemoveLoginRecords(l ...*LoginRecord) *UserUpdate {
	ids := make([]int64, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return uu.RemoveLoginRecordIDs(ids...)
}

// ClearRoles clears the "roles" edge to the Role entity.
func (uu *UserUpdate) ClearRoles() *UserUpdate {
	uu.mutation.ClearRoles()
	return uu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uu *UserUpdate) Save(ctx context.Context) (int, error) {
	uu.defaults()
	return withHooks(ctx, uu.sqlSave, uu.mutation, uu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uu *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := uu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uu *UserUpdate) Exec(ctx context.Context) error {
	_, err := uu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uu *UserUpdate) ExecX(ctx context.Context) {
	if err := uu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uu *UserUpdate) defaults() {
	if _, ok := uu.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		uu.mutation.SetUpdatedAt(v)
	}
}

func (uu *UserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64))
	if ps := uu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uu.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := uu.mutation.Account(); ok {
		_spec.SetField(user.FieldAccount, field.TypeString, value)
	}
	if value, ok := uu.mutation.Password(); ok {
		_spec.SetField(user.FieldPassword, field.TypeString, value)
	}
	if value, ok := uu.mutation.PasswordFailTimes(); ok {
		_spec.SetField(user.FieldPasswordFailTimes, field.TypeInt, value)
	}
	if value, ok := uu.mutation.AddedPasswordFailTimes(); ok {
		_spec.AddField(user.FieldPasswordFailTimes, field.TypeInt, value)
	}
	if value, ok := uu.mutation.Status(); ok {
		_spec.SetField(user.FieldStatus, field.TypeInt, value)
	}
	if value, ok := uu.mutation.AddedStatus(); ok {
		_spec.AddField(user.FieldStatus, field.TypeInt, value)
	}
	if uu.mutation.AuthClientsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.AuthClientsTable,
			Columns: []string{user.AuthClientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(authclient.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.AuthClientsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.AuthClientsTable,
			Columns: []string{user.AuthClientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(authclient.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.LoginRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.LoginRecordsTable,
			Columns: []string{user.LoginRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loginrecord.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RemovedLoginRecordsIDs(); len(nodes) > 0 && !uu.mutation.LoginRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.LoginRecordsTable,
			Columns: []string{user.LoginRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loginrecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.LoginRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.LoginRecordsTable,
			Columns: []string{user.LoginRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loginrecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.RolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   user.RolesTable,
			Columns: []string{user.RolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   user.RolesTable,
			Columns: []string{user.RolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uu.mutation.done = true
	return n, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (uuo *UserUpdateOne) SetUpdatedAt(t time.Time) *UserUpdateOne {
	uuo.mutation.SetUpdatedAt(t)
	return uuo
}

// SetAccount sets the "account" field.
func (uuo *UserUpdateOne) SetAccount(s string) *UserUpdateOne {
	uuo.mutation.SetAccount(s)
	return uuo
}

// SetNillableAccount sets the "account" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableAccount(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetAccount(*s)
	}
	return uuo
}

// SetPassword sets the "password" field.
func (uuo *UserUpdateOne) SetPassword(s string) *UserUpdateOne {
	uuo.mutation.SetPassword(s)
	return uuo
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillablePassword(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetPassword(*s)
	}
	return uuo
}

// SetPasswordFailTimes sets the "password_fail_times" field.
func (uuo *UserUpdateOne) SetPasswordFailTimes(i int) *UserUpdateOne {
	uuo.mutation.ResetPasswordFailTimes()
	uuo.mutation.SetPasswordFailTimes(i)
	return uuo
}

// SetNillablePasswordFailTimes sets the "password_fail_times" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillablePasswordFailTimes(i *int) *UserUpdateOne {
	if i != nil {
		uuo.SetPasswordFailTimes(*i)
	}
	return uuo
}

// AddPasswordFailTimes adds i to the "password_fail_times" field.
func (uuo *UserUpdateOne) AddPasswordFailTimes(i int) *UserUpdateOne {
	uuo.mutation.AddPasswordFailTimes(i)
	return uuo
}

// SetStatus sets the "status" field.
func (uuo *UserUpdateOne) SetStatus(i int) *UserUpdateOne {
	uuo.mutation.ResetStatus()
	uuo.mutation.SetStatus(i)
	return uuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableStatus(i *int) *UserUpdateOne {
	if i != nil {
		uuo.SetStatus(*i)
	}
	return uuo
}

// AddStatus adds i to the "status" field.
func (uuo *UserUpdateOne) AddStatus(i int) *UserUpdateOne {
	uuo.mutation.AddStatus(i)
	return uuo
}

// SetAuthClientsID sets the "auth_clients" edge to the AuthClient entity by ID.
func (uuo *UserUpdateOne) SetAuthClientsID(id int64) *UserUpdateOne {
	uuo.mutation.SetAuthClientsID(id)
	return uuo
}

// SetNillableAuthClientsID sets the "auth_clients" edge to the AuthClient entity by ID if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableAuthClientsID(id *int64) *UserUpdateOne {
	if id != nil {
		uuo = uuo.SetAuthClientsID(*id)
	}
	return uuo
}

// SetAuthClients sets the "auth_clients" edge to the AuthClient entity.
func (uuo *UserUpdateOne) SetAuthClients(a *AuthClient) *UserUpdateOne {
	return uuo.SetAuthClientsID(a.ID)
}

// AddLoginRecordIDs adds the "login_records" edge to the LoginRecord entity by IDs.
func (uuo *UserUpdateOne) AddLoginRecordIDs(ids ...int64) *UserUpdateOne {
	uuo.mutation.AddLoginRecordIDs(ids...)
	return uuo
}

// AddLoginRecords adds the "login_records" edges to the LoginRecord entity.
func (uuo *UserUpdateOne) AddLoginRecords(l ...*LoginRecord) *UserUpdateOne {
	ids := make([]int64, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return uuo.AddLoginRecordIDs(ids...)
}

// SetRolesID sets the "roles" edge to the Role entity by ID.
func (uuo *UserUpdateOne) SetRolesID(id int64) *UserUpdateOne {
	uuo.mutation.SetRolesID(id)
	return uuo
}

// SetNillableRolesID sets the "roles" edge to the Role entity by ID if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableRolesID(id *int64) *UserUpdateOne {
	if id != nil {
		uuo = uuo.SetRolesID(*id)
	}
	return uuo
}

// SetRoles sets the "roles" edge to the Role entity.
func (uuo *UserUpdateOne) SetRoles(r *Role) *UserUpdateOne {
	return uuo.SetRolesID(r.ID)
}

// Mutation returns the UserMutation object of the builder.
func (uuo *UserUpdateOne) Mutation() *UserMutation {
	return uuo.mutation
}

// ClearAuthClients clears the "auth_clients" edge to the AuthClient entity.
func (uuo *UserUpdateOne) ClearAuthClients() *UserUpdateOne {
	uuo.mutation.ClearAuthClients()
	return uuo
}

// ClearLoginRecords clears all "login_records" edges to the LoginRecord entity.
func (uuo *UserUpdateOne) ClearLoginRecords() *UserUpdateOne {
	uuo.mutation.ClearLoginRecords()
	return uuo
}

// RemoveLoginRecordIDs removes the "login_records" edge to LoginRecord entities by IDs.
func (uuo *UserUpdateOne) RemoveLoginRecordIDs(ids ...int64) *UserUpdateOne {
	uuo.mutation.RemoveLoginRecordIDs(ids...)
	return uuo
}

// RemoveLoginRecords removes "login_records" edges to LoginRecord entities.
func (uuo *UserUpdateOne) RemoveLoginRecords(l ...*LoginRecord) *UserUpdateOne {
	ids := make([]int64, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return uuo.RemoveLoginRecordIDs(ids...)
}

// ClearRoles clears the "roles" edge to the Role entity.
func (uuo *UserUpdateOne) ClearRoles() *UserUpdateOne {
	uuo.mutation.ClearRoles()
	return uuo
}

// Where appends a list predicates to the UserUpdate builder.
func (uuo *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	uuo.mutation.Where(ps...)
	return uuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uuo *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	uuo.fields = append([]string{field}, fields...)
	return uuo
}

// Save executes the query and returns the updated User entity.
func (uuo *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	uuo.defaults()
	return withHooks(ctx, uuo.sqlSave, uuo.mutation, uuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uuo *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := uuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uuo *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := uuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uuo *UserUpdateOne) ExecX(ctx context.Context) {
	if err := uuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uuo *UserUpdateOne) defaults() {
	if _, ok := uuo.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		uuo.mutation.SetUpdatedAt(v)
	}
}

func (uuo *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64))
	id, ok := uuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uuo.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := uuo.mutation.Account(); ok {
		_spec.SetField(user.FieldAccount, field.TypeString, value)
	}
	if value, ok := uuo.mutation.Password(); ok {
		_spec.SetField(user.FieldPassword, field.TypeString, value)
	}
	if value, ok := uuo.mutation.PasswordFailTimes(); ok {
		_spec.SetField(user.FieldPasswordFailTimes, field.TypeInt, value)
	}
	if value, ok := uuo.mutation.AddedPasswordFailTimes(); ok {
		_spec.AddField(user.FieldPasswordFailTimes, field.TypeInt, value)
	}
	if value, ok := uuo.mutation.Status(); ok {
		_spec.SetField(user.FieldStatus, field.TypeInt, value)
	}
	if value, ok := uuo.mutation.AddedStatus(); ok {
		_spec.AddField(user.FieldStatus, field.TypeInt, value)
	}
	if uuo.mutation.AuthClientsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.AuthClientsTable,
			Columns: []string{user.AuthClientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(authclient.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.AuthClientsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.AuthClientsTable,
			Columns: []string{user.AuthClientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(authclient.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.LoginRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.LoginRecordsTable,
			Columns: []string{user.LoginRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loginrecord.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RemovedLoginRecordsIDs(); len(nodes) > 0 && !uuo.mutation.LoginRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.LoginRecordsTable,
			Columns: []string{user.LoginRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loginrecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.LoginRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.LoginRecordsTable,
			Columns: []string{user.LoginRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loginrecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.RolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   user.RolesTable,
			Columns: []string{user.RolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   user.RolesTable,
			Columns: []string{user.RolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: uuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uuo.mutation.done = true
	return _node, nil
}
