// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AuthClient is the predicate function for authclient builders.
type AuthClient func(*sql.Selector)

// LoginRecord is the predicate function for loginrecord builders.
type LoginRecord func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
